export const profilData = [
  {
    id: 1,
    username: 'paul.martin',
    email: 'paul.martin@gmail.com',
    mdp: '1234',
    prenom: 'Paul',
    nom: 'Martin',
    genre: 'M',
    date_nai: '01/02/2002',
    age: '18',
    structure: 'AS Montpellier',
    coach: 'Coach Carter',
    statut: 'utilisateur',
    userType: 'adhérent',
    language: 'fr',
  },
  {
    id: 2,
    username: 'coach.carter',
    email: 'coach.carter@gmail.com',
    mdp: '1234',
    prenom: 'Coach',
    nom: 'Carter',
    genre: 'M',
    date_nai: '15/09/1990',
    structure: 'AS Montpellier',
    statut: 'gestionnaire de structure',
    userType: 'coach',
    language: 'fr',
  },
]
